# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-13 07:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160701_1528'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
