# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-26 23:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_delete_greeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spotted',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('attachment', models.URLField()),
                ('spam', models.BooleanField(default=False)),
                ('post_id', models.CharField(max_length=100)),
                ('dismissed', models.BooleanField(default=False)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
