# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotteds', '0002_auto_20170205_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingspotted',
            name='polemic',
            field=models.BooleanField(default=False),
        ),
    ]
