# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotteds', '0003_pendingspotted_polemic'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingspotted',
            name='attachment_safe',
            field=models.BooleanField(default=False),
        ),
    ]
