# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotteds', '0005_pendingspotted_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingspotted',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='spotted',
            name='api_id',
            field=models.IntegerField(null=True),
        ),
    ]
