# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotteds', '0007_auto_20170516_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingspotted',
            name='share_with_crush',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='spotted',
            name='share_with_crush',
            field=models.BooleanField(default=True),
        ),
    ]
