# Generated by Django 2.0.3 on 2018-03-11 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotteds', '0008_auto_20170704_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingspotted',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pendingspotted',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_targeted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotted',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_spotteds', to='moderation.Moderator'),
        ),
        migrations.AlterField(
            model_name='spotted',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='spotted',
            name='target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted', to=settings.AUTH_USER_MODEL),
        ),
    ]
