# Generated by Django 2.0.3 on 2018-06-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotteds', '0009_auto_20180311_0411'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spotted',
            options={'ordering': ['-id']},
        ),
    ]
