# Generated by Django 2.0.3 on 2018-06-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotteds', '0010_auto_20180614_0110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingspotted',
            options={'ordering': ['-id']},
        ),
    ]
