# Generated by Django 2.0.3 on 2018-06-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NagMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nag_id', models.CharField(max_length=32)),
                ('message', models.TextField(null=True)),
                ('enable', models.BooleanField(default=False)),
            ],
        ),
    ]
