# Generated by Django 2.0.3 on 2018-07-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='scopes',
            field=models.CharField(default='[]', max_length=2000),
        )
    ]
