# Generated by Django 2.0.3 on 2018-07-02 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_auto_20180701_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='expires',
            field=models.IntegerField(),
        ),
    ]
