# Generated by Django 2.0.3 on 2018-07-02 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20180701_2335'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
