# Generated by Django 2.0.3 on 2018-03-28 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_auto_20170703_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookuser',
            name='hd_thumbnail',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='facebookuser',
            name='hd_thumbnail_age',
            field=models.DateTimeField(null=True),
        ),
    ]
