# Generated by Django 2.0.3 on 2018-03-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_auto_20180328_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='hd_thumbnail',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='thumbnail',
            field=models.URLField(null=True),
        ),
    ]
