# Generated by Django 2.0.3 on 2018-05-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_auto_20180328_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='hd_thumbnail',
            field=models.URLField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='link',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='facebookuser',
            name='thumbnail',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
