# Generated by Django 2.0.3 on 2018-05-01 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_auto_20180501_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facebookuser',
            name='hd_thumbnail',
        ),
        migrations.RemoveField(
            model_name='facebookuser',
            name='hd_thumbnail_age',
        ),
        migrations.RemoveField(
            model_name='facebookuser',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='facebookuser',
            name='thumbnail_age',
        ),
    ]
